// 题卡、分隔栏、课程切换、顶部功能区模板
function sub(it){return nodeAt(it.c,it.path||firstPath(it.c))}
function key(it){return sk(it.c,it.path||firstPath(it.c))}
function title(c){let t=c.t||'';return c._n?(String(c._n).padStart(c._pad||1,'0')+'｜'+t):t}
function routeLevelHtml(c,q,path){let p=pa0(path),parent=nodeAt(c,q),pr=prog(c,q),lv=q.length,hname=q.length?snameAt(c,q.slice(0,-1),q[q.length-1]):'',head=q.length?`<div class="sbh"><span>${E(hname||parent.t||parent.title||'下级路线')}</span><em>掌握 ${E(pr.label)}</em></div>`:'',rows=subRows(parent).map((r,idx)=>{let i=r.i,np=q.concat(i),child=r.x,ok=ulAt(c,q,i),done=donePath(c,np),on=p[lv]===i,name=snameAt(c,q,i),has=hs(child),cp=has?prog(c,np):null,tail=has?`<small>${E(cp.label)}</small>`:'',a=sq(parent)&&idx?'<span class="sba" aria-hidden="true">⮕</span>':'';return `${a}<button class="sbx ${has?'has-sub':''} ${on?'on':''} ${ok?'':'lkd'} ${done?'done':''}" data-path="${E(ps0(np))}" ${ok?'':'disabled'}><span class="sbt">${ok?'':'🔒 '}${E(name)}</span>${tail}</button>`}).join('');return `<div class="sbr" data-level="${lv+1}">${head}<div class="sb">${rows}</div><div class="bar rbar" title="${E(pr.label)}"><b style="width:${pr.frac*100}%"></b></div></div>`}
function routeHtml(c,path){if(!hs(c))return '';let p=pa0(path),out=[],q=[];for(;;){let parent=nodeAt(c,q);if(!hs(parent))break;out.push(routeLevelHtml(c,q,p));let next=p[q.length];if(next===undefined||!nodeAt(c,q.concat(next)))break;q=q.concat(next)}return out.join('')}
function us(it){let p=prog(it.c,[]);it.el.querySelector('.lv').textContent='掌握 '+p.label;let r=it.el.querySelector('.routes');if(r){r.innerHTML=routeHtml(it.c,it.path||firstPath(it.c));r.querySelectorAll('.sbx').forEach(b=>b.onclick=()=>sw(it,b.dataset.path));return}let b=it.el.querySelector('.mainbar b');b&&(b.style.width=p.frac*100+'%')}
function box(c){let h=hs(c),f=firstPath(c),first=nodeAt(c,f),p=prog(c,[]),b=h?`<div class="routes">${routeHtml(c,f)}</div>`:`<div class="bar mainbar"><b style="width:${p.frac*100}%"></b></div>`;return `<article class="st" data-t="${E((c.tags||c.type||'choice').toString())}">${F}${inn}<div class="tt"><div class="tp"><span class="pl tm">0.0 秒</span><span class="pl ty">${E(kg(first))}</span><span class="pl lv">掌握 ${E(p.label)}</span></div><div class="ti">${E(title(c))}</div>${b}<div class="q">点击开始</div><div class="cs"></div><div class="tl"><button class="go stt">开始</button><div class="ex"></div></div><div class="fb">${h?E(pathName(c,f)+'｜未开始｜'+lt(nodeAt(c,pa0(f).slice(0,-1)))):'未开始'}</div></div></section></article>`}
function sep(c){let x=E(c.x||c.t||'');return `<article class="st sp"><div class="tt"><div class="sl"><i></i><span>${x}</span><i></i></div></div></article>`}
function sg(x){return x.selectorGroup||x.group||x.category||''}
function sn(x,i){return x.selectorNo||x.no||String(i+1)}
function sel(L){let blocks=[],i=0;while(i<L.length){let g=sg(L[i]);if(g){let a=[],j=i;while(j<L.length&&sg(L[j])===g)a.push([L[j],j]),j++;blocks.push(`<div class="cgsec"><div class="sl cgsep"><i></i><span>${E(g)}</span><i></i></div><div class="cnums">${a.map(([x,k])=>{let name=x.t||x.title||x.id,no=sn(x,k);return `<button class="cb cnum ${x.id==C?'on':''}" data-c="${E(x.id)}" title="${E(name)}" aria-label="${E('切换课程 '+no+'：'+name)}">${E(no)}</button>`}).join('')}</div></div>`);i=j}else{let x=L[i],name=x.t||x.title||x.id;blocks.push(`<button class="cb cnorm ${x.id==C?'on':''}" data-c="${E(x.id)}" title="${E(name)}" aria-label="${E('切换课程：'+name)}">${E(name)}</button>`);i++}}return `<article class="st sel">${F}${inn}<div class="tt"><div class="cp"><div class="ti">课程切换</div><div class="cl cltier">${blocks.join('')}</div></div></div></section></article>`}
function tools(){return `<section class="tb"><strong>功能区</strong><div class="ta"><button class="tbx" data-act="cards" data-tip="查看已收集卡牌；完美测试模式显示本课程全部卡牌且不写存档">卡牌专区</button><button class="tbx" data-act="settings" data-tip="导入/导出本地存档，不影响课程文件">设置</button></div></section>`}
