(function(){
const T=window.GR3,$=s=>document.querySelector(s),view=$('#view'),mode=$('#mode'),width=$('#width'),skew=$('#skew'),wv=$('#wv'),sv=$('#sv'),sc=new T.Scene(),cam=new T.OrthographicCamera(-2.4,2.4,2.4,-2.4,.1,100),ren=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true}),ctl=new T.OrbitControls(cam,ren.domElement),geo=new T.BoxGeometry(2,2,2),mat=new T.MeshBasicMaterial({color:0xffffff,polygonOffset:true,polygonOffsetFactor:1,polygonOffsetUnits:1}),box=new T.Mesh(geo,mat),rig=new T.Group(),edges=new T.EdgesGeometry(geo);let line=null,lg=null,lm=null,ang=0,ro;
sc.background=new T.Color(0xedf0f1);rig.matrixAutoUpdate=false;rig.add(box);sc.add(rig);cam.position.set(0,0,6);cam.lookAt(0,0,0);ctl.enableDamping=true;ctl.enablePan=false;view.append(ren.domElement);
function clear(){if(!line)return;box.remove(line);line.traverse?.(x=>{x.geometry&&x.geometry!==geo&&x.geometry.dispose();x.material&&x.material.dispose()});lg?.dispose();lm?.dispose();line=lg=lm=null}
function tubes(){let p=edges.attributes.position.array,g=new T.Group(),r=+.012*+width.value,a=new T.Vector3(),b=new T.Vector3(),d=new T.Vector3(),q=new T.Quaternion();for(let i=0;i<p.length;i+=6){a.set(p[i],p[i+1],p[i+2]);b.set(p[i+3],p[i+4],p[i+5]);d.subVectors(b,a);let x=new T.Mesh(new T.CylinderGeometry(r,r,d.length(),10),new T.MeshBasicMaterial({color:0x263944}));x.position.copy(a).add(b).multiplyScalar(.5);q.setFromUnitVectors(new T.Vector3(0,1,0),d.clone().normalize());x.quaternion.copy(q);g.add(x)}return g}
function edge(){clear();if(mode.value==='wide'){lg=new T.LineSegmentsGeometry().setPositions(edges.attributes.position.array);lm=new T.LineMaterial({color:0x263944,linewidth:+width.value,depthWrite:false});lm.resolution.set(view.clientWidth,view.clientHeight);line=new T.LineSegments2(lg,lm)}else if(mode.value==='tube')line=tubes();else{lm=new T.LineBasicMaterial({color:0x263944,depthWrite:false});line=new T.LineSegments(edges.clone(),lm)}line.renderOrder=2;box.add(line)}
function size(){let w=view.clientWidth,h=view.clientHeight,a=w/h,v=2.15;cam.left=-v*a;cam.right=v*a;cam.top=v;cam.bottom=-v;cam.updateProjectionMatrix();ren.setPixelRatio(Math.min(devicePixelRatio,2));ren.setSize(w,h,false);lm?.resolution?.set(w,h)}
function draw(){let k=+skew.value;rig.matrix.set(1,0,-k,0,0,1,-k,0,0,0,1,0,0,0,0,1);box.rotation.y=ang;wv.value=width.value+' px';sv.value=(+skew.value).toFixed(2);edge();view.dataset.mode=mode.value;ren.render(sc,cam)}
function loop(){requestAnimationFrame(loop);ctl.update();ren.render(sc,cam)}
mode.onchange=draw;width.oninput=draw;skew.oninput=draw;$('#left').onclick=()=>{ang-=Math.PI/2;draw()};$('#right').onclick=()=>{ang+=Math.PI/2;draw()};$('#reset').onclick=()=>{ang=0;cam.position.set(0,0,6);ctl.target.set(0,0,0);ctl.update();draw()};$('#shot').onclick=()=>{ren.render(sc,cam);let a=document.createElement('a');a.download=`cube-${mode.value}-${width.value}px.png`;a.href=ren.domElement.toDataURL('image/png');a.click()};ro=new ResizeObserver(size);ro.observe(view);size();draw();loop();
})();
