(function(){
  const pk=a=>a[Math.floor(Math.random()*a.length)];
  const n=(a,b)=>a+Math.floor(Math.random()*(b-a+1));
  const one=x=>Math.round(x*10)/10;
  const pct=x=>`${one(x)}%`;
  const num=x=>String(Math.round(x));
  const uq=a=>[...new Set(a.map(String))];
  const sh=a=>a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]);
  const op=(a,b,l=4)=>sh([String(a),...sh(uq(b).filter(x=>x!==String(a))).slice(0,l-1)]);
  const R=(q,a,pool,hint,solution,extra={})=>Object.assign({q,a:String(a),pool:pool.map(String),hint,solution},extra);
  const cid='data_analysis_speed_08';
  const Q=(id,title,tags,mk,type)=>({id,title,t:title,type:type||tags[0],tags,mk,makeQuestion:mk});
  const C=(id,title,tags,subs,unlockMode='all')=>({id,title,t:title,type:tags[0],tags,unlockMode,subs});
  const sec=title=>Game.addLessonTopic(cid,{k:'s',t:title});
  const add=t=>Game.addLessonTopic(cid,t);
  const done=title=>Game.finishLesson(cid,title);
  const approx=(x,d=1)=>String((Math.round(x*Math.pow(10,d))/Math.pow(10,d)).toFixed(d));
  Game.beginLesson(cid);
  window.EX={pk,n,one,pct,num,op,R,Q,C,sec,add,done,approx};
})();
