// Auto-generated by tools/check_fix_lesson_catalogs.js. Do not edit by hand.
(function(){
  window.Game=window.Game||{};
  Game.lessonFileLists=Game.lessonFileLists||{};
  Game.lessonFileLists["placeholder_math"]=[
    "placeholder_math.js"
  ];
})();
