#!/usr/bin/env node
/*
  Scan every lesson folder, compare its internal _lesson_files.js list with
  the real .js files in that folder, then rewrite the list if needed.

  Usage:
    node tools/check_fix_lesson_catalogs.js
    node tools/check_fix_lesson_catalogs.js --check   # only report, do not write
*/
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const lessonsDir = path.join(root, 'lessons');
const listFileName = '_lesson_files.js';
const checkOnly = process.argv.includes('--check') || process.argv.includes('-c');

function rel(p) {
  return path.relative(root, p).split(path.sep).join('/');
}

function lessonFileSort(a, b) {
  const rank = f => f === '_common.js' ? 0 : (f === '_finish.js' ? 2 : 1);
  const ra = rank(a), rb = rank(b);
  if (ra !== rb) return ra - rb;

  const num = f => {
    const m = String(f).match(/^(\d+)/);
    return m ? Number(m[1]) : Number.MAX_SAFE_INTEGER;
  };
  const na = num(a), nb = num(b);
  if (na !== nb) return na - nb;

  const aa = String(a).toLowerCase(), bb = String(b).toLowerCase();
  if (aa < bb) return -1;
  if (aa > bb) return 1;
  return String(a) < String(b) ? -1 : (String(a) > String(b) ? 1 : 0);
}

function normalizeLessonFiles(files) {
  return [...new Set((files || [])
    .map(file => String(file || '').trim())
    .filter(Boolean)
    .filter(file => file !== listFileName)
    .filter(file => /^[^/\\?#]+\.js$/i.test(file))
  )].sort(lessonFileSort);
}

function arrayEquals(a, b) {
  return a.length === b.length && a.every((v, i) => v === b[i]);
}

function diff(a, b) {
  const bs = new Set(b);
  return a.filter(x => !bs.has(x));
}

function writeBody(folder, files) {
  return '// Auto-generated by tools/check_fix_lesson_catalogs.js. Do not edit by hand.\n' +
`(function(){\n  window.Game=window.Game||{};\n  Game.lessonFileLists=Game.lessonFileLists||{};\n  Game.lessonFileLists[${JSON.stringify(folder)}]=${JSON.stringify(files, null, 2).replace(/^/gm, '  ').trim()};\n})();\n`;
}

function scanActualFiles(dir) {
  return normalizeLessonFiles(fs.readdirSync(dir)
    .filter(file => fs.statSync(path.join(dir, file)).isFile())
    .filter(file => file.endsWith('.js'))
  );
}

function readDeclaredList(folder, filePath) {
  if (!fs.existsSync(filePath)) {
    return { exists: false, files: [], keys: [], error: null };
  }

  try {
    const code = fs.readFileSync(filePath, 'utf8');
    const Game = {};
    const sandbox = {
      window: {},
      Game,
      console: { log(){}, warn(){}, error(){} }
    };
    sandbox.window.Game = Game;
    vm.createContext(sandbox);
    vm.runInContext(code, sandbox, { timeout: 1000, filename: rel(filePath) });
    const lists = Game.lessonFileLists || sandbox.window.LESSON_FILE_LISTS || {};
    const keys = Object.keys(lists);
    return {
      exists: true,
      files: normalizeLessonFiles(lists[folder]),
      keys,
      error: null
    };
  } catch (err) {
    return { exists: true, files: [], keys: [], error: err && err.message ? err.message : String(err) };
  }
}

function printList(label, items) {
  if (!items.length) return;
  console.log(`    ${label}:`);
  for (const item of items) console.log(`      - ${item}`);
}

function itemFolder(item) {
  if (!item) return '';
  if (typeof item === 'string') return item;
  return item.folder || item.id || '';
}

function readCatalogFolders() {
  const catalogPath = path.join(root, 'catalog.js');
  if (!fs.existsSync(catalogPath)) {
    return { exists: false, folders: [], error: null };
  }
  try {
    const code = fs.readFileSync(catalogPath, 'utf8');
    const Game = {};
    const sandbox = {
      window: {},
      Game,
      console: { log(){}, warn(){}, error(){} }
    };
    sandbox.window.Game = Game;
    vm.createContext(sandbox);
    vm.runInContext(code, sandbox, { timeout: 1000, filename: 'catalog.js' });
    const ctl = Game.ctl || {};
    const groups = Array.isArray(ctl.selectorGroups) ? ctl.selectorGroups : [];
    const grouped = [];
    for (const group of groups) {
      const source = Array.isArray(group.items) ? group.items : (Array.isArray(group.folders) ? group.folders : []);
      for (const item of source) {
        const folder = itemFolder(item);
        if (folder) grouped.push(folder);
      }
    }
    const standalone = Array.isArray(ctl.folders) ? ctl.folders.map(itemFolder).filter(Boolean) : [];
    return { exists: true, folders: [...new Set([...grouped, ...standalone])], error: null };
  } catch (err) {
    return { exists: true, folders: [], error: err && err.message ? err.message : String(err) };
  }
}

function printCatalogReport(actualFolders) {
  const catalog = readCatalogFolders();
  console.log('');
  console.log('主界面 catalog.js 检查：');
  if (!catalog.exists) {
    console.log('  [警告] 根目录没有 catalog.js。');
    return;
  }
  if (catalog.error) {
    console.log('  [警告] catalog.js 读取失败：' + catalog.error);
    return;
  }
  const missingDirs = diff(catalog.folders, actualFolders);
  const unlistedDirs = diff(actualFolders, catalog.folders);
  console.log('  catalog 声明课程数：' + catalog.folders.length);
  console.log('  lessons 实际目录数：' + actualFolders.length);
  if (!missingDirs.length && !unlistedDirs.length) {
    console.log('  状态：OK，catalog.js 与 lessons/ 目录一致。');
  } else {
    console.log('  状态：发现不一致。注意：本工具只自动修复每课内部 _lesson_files.js，不会擅自重写主界面分组。');
    printList('catalog 写了但 lessons/ 不存在', missingDirs);
    printList('lessons/ 存在但 catalog 未写入，主界面不会显示', unlistedDirs);
  }
}

if (!fs.existsSync(lessonsDir)) {
  console.error('[失败] 找不到 lessons/ 目录：' + lessonsDir);
  process.exit(1);
}

console.log('========================================');
console.log('课程内部清单扫描' + (checkOnly ? '（只检查，不写入）' : '与自动修复'));
console.log('根目录：' + root);
console.log('课程目录：' + rel(lessonsDir));
console.log('清单文件：' + listFileName);
console.log('========================================');

const folders = fs.readdirSync(lessonsDir)
  .filter(folder => fs.statSync(path.join(lessonsDir, folder)).isDirectory())
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

printCatalogReport(folders);

let total = 0;
let ok = 0;
let fixed = 0;
let skipped = 0;
let errors = 0;

for (const folder of folders) {
  const dir = path.join(lessonsDir, folder);
  const listPath = path.join(dir, listFileName);
  const actual = scanActualFiles(dir);

  if (!actual.length) {
    skipped++;
    console.log(`\n[跳过] ${folder}`);
    console.log('    原因：目录内没有可加载的课程 .js 文件。');
    continue;
  }

  total++;
  const declared = readDeclaredList(folder, listPath);
  const missing = diff(actual, declared.files);
  const extra = diff(declared.files, actual);
  const sameSet = missing.length === 0 && extra.length === 0;
  const sameOrder = arrayEquals(actual, declared.files);
  const wrongKey = declared.keys.length > 0 && !declared.keys.includes(folder);
  const generated = writeBody(folder, actual);
  const oldBody = fs.existsSync(listPath) ? fs.readFileSync(listPath, 'utf8') : '';
  const needsWrite = oldBody !== generated;

  let status = 'OK';
  if (!declared.exists) status = '缺少清单';
  else if (declared.error) status = '清单语法错误';
  else if (wrongKey) status = '课程名写错';
  else if (!sameSet) status = '文件列表写错';
  else if (!sameOrder) status = '顺序不一致';
  else if (needsWrite) status = '格式待统一';

  console.log(`\n[${status === 'OK' ? 'OK' : (checkOnly ? '发现问题' : '已修复')}] ${folder}`);
  console.log(`    实际脚本数：${actual.length}`);
  console.log(`    清单脚本数：${declared.files.length}`);
  console.log(`    清单路径：${rel(listPath)}`);

  if (declared.error) console.log('    语法错误：' + declared.error);
  if (wrongKey) console.log('    清单内课程名：' + declared.keys.join(', ') + '，应为：' + folder);
  printList('清单缺少', missing);
  printList('清单多写/文件不存在', extra);
  if (sameSet && !sameOrder) console.log('    顺序：已按 _common.js → 数字文件 → _finish.js 重新排序。');

  console.log('    当前正确文件列表：');
  for (const file of actual) console.log('      ' + file);

  if (status === 'OK') {
    ok++;
  } else {
    if (!checkOnly) fs.writeFileSync(listPath, generated, 'utf8');
    fixed++;
  }

  if (declared.error) errors++;
}

console.log('\n========================================');
console.log('汇总');
console.log('课程目录数：' + total);
console.log('原本正确：' + ok);
console.log((checkOnly ? '发现需修复：' : '已修复/重写：') + fixed);
console.log('跳过空目录：' + skipped);
console.log('清单语法错误：' + errors);
console.log('========================================');

if (checkOnly && fixed > 0) {
  console.log('提示：去掉 --check 重新运行即可自动修复。');
}
